### ISSUE TITLE
Adding License?

### ISSUE THREAD

**Issue by MartinHell** [lekpamartin/uptimerobot_exporter#6]
Hi,

Could a license be added to this repository? Right now we can't use this code because of it missing a license.

**Comment by lekpamartin** [comment]
Hi,

It is free to use. you can suggest a licence?

**Comment by MartinHell** [comment]
I would suggest MIT License. But I think you would need to have @billimek approval for adding the license as well since he has commits in the repository.

https://choosealicense.com/licenses/mit/

Also if he has a suggestion for another license I'm open for suggestions as well:)

**Comment by billimek** [comment]
I usually use Apache 2 for my repos, but MIT works as well.  I'm pretty easy!

**Comment by MartinHell** [comment]
Thanks for adding the license. Closing this ticket
